### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'classify')

### ISSUE THREAD

**Issue by marleyjaffe** [bertmelis/immich-machine-learning-no-avx#1]
Unable to successfully run machine learning container. I was getting an error about being unable to download the necessary file which was fixed with the dns variable but I am now running into the below error.

**Error Log**
```
today at 2:20:38 PMError reading file  TypeError: Cannot read properties of undefined (reading 'classify')
today at 2:20:38 PM    at ImageClassifierService.tagImage (/usr/src/app/dist/image-classifier/image-classifier.service.js:36:63)
today at 2:20:38 PM    at ImageClassifierController.tagImage (/usr/src/app/dist/image-classifier/image-classifier.controller.js:23:50)
today at 2:20:38 PM    at /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:38:29
today at 2:20:38 PM    at runMicrotasks (<anonymous>)
today at 2:20:38 PM    at processTicksAndRejections (node:internal/process/task_queues:96:5)
today at 2:20:38 PM    at async /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
today at 2:20:38 PM    at async /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

**Relebant Docker Compose**
```
  immich-machine-learning:
    container_name: immich_machine_learning
    # image: altran1502/immich-machine-learning:release
    image: bertmelis1/immich-machine-learning-noavx:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    networks:
      - immich
      - socket_proxy
    dns:
      - "1.1.1.1"
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    restart: always
```

**Comment by bertmelis** [comment]
I'm unable to reproduce this.

Please try this:
- download [libtensorflow.tar.gz](https://github.com/bertmelis/immich-machine-learning-no-avx/blob/main/libtensorflow.tar.gz) from this repo.

- create a `Containerfile`:
```
FROM altran1502/immich-machine-learning:release

COPY libtensorflow.tar.gz node_modules/@tensorflow/tfjs-node/deps/libtensorflow.tar.gz

RUN apt-get update && \
    apt-get -y --no-install-recommends install libomp-dev && \
    apt-get clean && \
    cd node_modules/@tensorflow/tfjs-node/deps && \
    tar -xf libtensorflow.tar.gz && \
    rm libtensorflow.tar.gz
```

- adjust your compose file, remove the image and add the build context:

```
  immich-machine-learning:
    build: ./
    container_name: immich-machine-learning
    hostname: immich-machine-learning
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always
```

Your container engine will now build the image instead of fetching it. So you will use the latest version.
To update, bring down the stack, remove the machine learning image and bring up again.
